// <auto-generated />
using System;
using ApiDemo2.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiDemo2.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiDemo2.models.ChildModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentModelId");

                    b.ToTable("ChildModels");
                });

            modelBuilder.Entity("ApiDemo2.models.ParentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ParentModels");
                });

            modelBuilder.Entity("ApiDemo2.models.ChildModel", b =>
                {
                    b.HasOne("ApiDemo2.models.ParentModel", null)
                        .WithMany("ChildModels")
                        .HasForeignKey("ParentModelId");
                });

            modelBuilder.Entity("ApiDemo2.models.ParentModel", b =>
                {
                    b.Navigation("ChildModels");
                });
#pragma warning restore 612, 618
        }
    }
}
